FORMAT: 1A
HOST: http://www.google.com

# SensorDefinitionAPI
An API for defining Sensors. We define both data about the physical sensor itself, and MetaData about the information the Sensor delivers

# Group General
## Hardware Collection [/sensors]

# Group Hardware
Hardware related resource of the **Sensor Definition**

## Hardware Collection [/sensors/{sensorID}/description/hardware]

# Group Firmware
Firmware related resource of the **Sensor Definition**

## Firmware Collection [/sensor/{sensorID}/description/firmware]

# Group Readings
Firmware related resource of the **Sensor Definition**

## Readings Collection [/sensor/{sensorID}/description/readings]



